chatApp/urls.py
from django.urls import path

from . import views

app_name = 'chatApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),

]

codenames/urls.py
from django.urls import path

from . import views

app_name = 'codenames'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),
]

loginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings
from . import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('loginApp.urls'), name='loginApp'),
    path('home/', include('smartHome.urls'), name='smartHome'),
    path('chat/', include('chatApp.urls'), name='chatApp'),
    path('codenames/', include('codenames.urls'), name='codenames'),
    path('', homepage.homepage, name='homepage')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codenames/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import random

chatrooms = {}

# Create your views here.


@login_required(login_url='/recipes/login?next=/codenames/')
def homepage(request):
    return render(request, 'codenames/home.html')


@login_required(login_url='/recipes/login?next=/codenames/')
def create_room(request):
    if request.method == 'GET':
        room_id = random.randint(1000, 9999)
        while room_id in chatrooms.keys():
            room_id = random.randint(1000, 9999)
        chatrooms[room_id] = 1

        print("A szoba azonositoja", room_id)
        return render(request, 'codenames/room.html', {"room_id": room_id})

    return render(request, 'codenames/home.html', {"error": 'Valami hiba tortent a szoba letrehozasanal!'})


@login_required(login_url='/recipes/login?next=/codenames/')
def join_room(request):
    if request.method == 'POST':
        join_code = request.POST.get('joinCode', None)

        if join_code:
            return render(request, 'codenames/room.html', {'room_id': join_code})


def exit_room(request):
    return render(request, 'codenames/home.html', {})

templates/codenames/home.html
{% extends "loginApp/header.html" %}

{% block title %}Fokepernyo{% endblock %}

{% block content %}
{% if user.is_authenticated %}



    <h1>Hello {{ user.username }}</h1>
    <a href="{% url 'codenames:create_room' %}" class="btn btn-primary mb-3">Szoba letrehozasa</a>

    <form action="{% url 'codenames:join_room' %}" method="post">
    <div class="form-group">
        {% csrf_token %}
    <input id="joinCode" name="joinCode" class="form-control" type="number" size="4" placeholder="Room join code" />
    <input type="submit" class="btn btn-success mt-3" value="csatlakozas" />
    </div>

    </form>

{% endif %}

{% endblock %}

templates/codenames/room.html
{% extends 'loginApp/header.html' %}

{% block title %}{{ room_id }} számú szoba{% endblock %}

{% block content %}

    <div class="flex-container mt-4">
        <h2>#{{ room_id }} szoba, jatekosok szama: <span id="playersCount">0</span> db</h2>
    </div>

    <div class="flex-container mt-4" style="width: 100%;" id="playersList">
    <div class="row">
        <div id="pirosCsapat" class="col">
            <span>Piros csapat:</span><button class="btn" id="red_team" name="joinButton"><i class="fas fa-plus"></i></button>
            <ul id='pirosCsapatUl' class="list-group lists">
            </ul>
            <span>spyMaster:</span><button class="btn" id="red_master" name="joinButton"><i class="fas fa-plus"></i></button>
            <ul id="pirosSpyMaster" class="list-group"></ul>
        </div>
        <div id="kekCsapat" class="col">
          <span>Kek csapat:</span><button class="btn" id="blue_team" name="joinButton"><i class="fas fa-plus"></i></button>
          <ul id='kekCsapatUl' class="list-group lists">
            </ul>
            <span>spyMaster:</span><button class="btn" id="blue_master" name="joinButton"><i class="fas fa-plus"></i></button>
            <ul id="kekSpyMaster" class="list-group"></ul>
        </div>
        <div id="nincsCsapat" class="col">
          <p>Nincs csapat</p>
            <ul id='nincsCsapatUl' class="list-group lists">
            </ul>
        </div>
    </div>
    </div>

    <div id="game" class="flex-container mt-3" style="min-height: 500px;">

    </div>

    <div class="row ml-1 justify" style="height: 5%; display: none">
        <input  type="text" style="width: 93%" class="mr-2" id="textMessage">
        <input type="button" class="btn btn-primary" value="Send" id="sendBtn">
    </div>

    {{ room_id|json_script:"room-id" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-id').textContent);
        var players;

        const socket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/codenames/'
            + roomName
            + '/'
        );

        socket.onopen = function (e) {
            socket.send(JSON.stringify({
                'event': 'socket_connected',
                'username': '{{ user.username }}'
            }))
        }

        socket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
            if (data.event == 'join')
            {
                count = data.players.length;
                $("#playersCount").text(count);
                players = data.players;
                console.log(players)
                renderPlayerList(players)
            }
            else if (data.event = 'error') {
                if (data.to_user == '{{ user.username }}')
                {
                    alert(data.msg);
                }
            }
        };

        socket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
            window.location.href = "{% url 'codenames:exit_room' %}";
        };


        document.querySelector('#sendBtn').onclick = function(e) {

            socket.send(JSON.stringify({
                'sender': "{{ user.username }}",
                'message': message
            }));

        };

        $("button[name='joinButton']").click( function () {
            let a = $(this);
            console.log(a.attr('id'));

            socket.send(JSON.stringify({
                'event': 'change_team',
                'user': '{{ user.username }}',
                'team': a.attr('id')
            }));
        });

        function renderPlayerList(players)
        {
            // a listak kiuritese,
            $("#nincsCsapatUl").html('')
            $("#kekCsapatUl").html('')
            $("#pirosCsapatUl").html('')
            $("#kekSpyMaster").html('')
            $("#pirosSpyMaster").html('')


            for(var i = 0; i<players.length; i++)
            {
                let player = players[i];
                if(player.team == 'red'){
                    if (player.master){
                        $("#pirosSpyMaster").append("<li class='list-group-item list-group-item-danger'>"+ player.name +"</li>");
                    } else {
                        $("#pirosCsapatUl").append("<li class='list-group-item list-group-item-danger'>"+ player.name +"</li>");
                    }
                } else if (player.team == 'blue') {
                    if (player.master){
                    $("#kekSpyMaster").append("<li class='list-group-item list-group-item-primary'>"+ player.name +"</li>");
                    } else {
                    $("#kekCsapatUl").append("<li class='list-group-item list-group-item-primary'>"+ player.name +"</li>");
                    }
                } else {
                    $("#nincsCsapatUl").append("<li class='list-group-item list-group-item-secondary'>"+ player.name +"</li>");
                }
            }
        }
    </script>

{% endblock %}