chatApp/urls.py
from django.urls import path

from . import views

app_name = 'chatApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),

]

codenames/urls.py
from django.urls import path

from . import views

app_name = 'codenames'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),
]

loginApp/urls.py
from django.urls import path

from . import views

app_name = 'loginApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("register/", views.register_request, name='register'),
    path("login/", views.login_request, name='login'),
    path("logout/", views.logout_request, name='logout'),
    path('permission/', views.permission_denied, name='permission'),
    path("allergies/", views.allergiesList, name="allergies"),
    path("allergies/new", views.add_allergie, name='add_allergie'),
    path("allergies/ajax/get_allergies_id", views.get_allergies_id, name='get_allergies_id'),
    path("allergies/<int:allergies_id>/view", views.view_allergie, name="allergies_view"),
    path("allergies/<int:allergies_id>/edit", views.update_allergie, name="allergies_edit"),
    path("allergies/<int:allergies_id>/delete", views.del_allergies, name="allergies_del"),
    path("categories/", views.categoryList, name='categories'),
    path("category/new", views.add_category, name="add_category"),
    path("category/ajax/get_category_id", views.get_category_id, name='get_category_id'),
    path("category/<int:category_id>/view", views.view_category, name='category_view'),
    path("category/<int:category_id>/edit", views.update_category, name="category_edit"),
    path("category/<int:category_id>/delete", views.del_category, name='category_del'),
    path("recipe_list/", views.recipe_list, name='recipes'),
    path("recipes/new", views.add_recipe, name='add_recipe'),
    path("recipes/<str:recipe_id>/view", views.view_recipe, name='recipe_view'),
    path("recipes/<str:recipe_id>/edit", views.update_recipe, name='recipe_edit'),
    path("recipes/<str:recipe_id>/pdf", views.recipe_to_pdf, name='recipe_pdf_generate'),
    path("recipes/<str:recipe_id>/delete", views.delete_recipe, name='recipe_delete'),
    path("ingredients/", views.ingredientList, name='categories'),
    path("ingredient/new", views.add_ingredient, name="add_ingredient"),
    path("ingredient/<int:ingredient_id>/view", views.view_ingredient, name='ingredient_view'),
    path("ingredient/<int:ingredient_id>/edit", views.update_ingredient, name="ingredient_edit"),
    path("ingredient/<int:ingredient_id>/delete", views.delete_ingredient, name='ingredient_del'),
    path("login_api/", views.save_api_call, name='login_api'),
    path("login_with_api/", views.api_login, name='login_with_api'),
    path("storage/", views.storage, name='storage')
]

loginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings
from . import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('loginApp.urls'), name='loginApp'),
    path('home/', include('smartHome.urls'), name='smartHome'),
    path('chat/', include('chatApp.urls'), name='chatApp'),
    path('codenames/', include('codenames.urls'), name='codenames'),
    path('', homepage.homepage, name='homepage')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartHome/urls.py
from django.urls import path

from . import views

app_name = 'smartHome'

urlpatterns = [
    path("index/", views.homepage, name='homepage'),
    path("ajax_switch/", views.ajax_switch, name='ajax_switch'),
    path("login_rfid/", views.rfid_login, name='rfid_login'),
]

loginApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.conf import settings

# Create your models here.


class Storage(models.Model):
    def __str__(self):
        return f"{self.pk}"


class APIModel(models.Model):
    id = models.AutoField(unique=True, blank=False, primary_key=True, auto_created=True)
    username = models.CharField(max_length=200, unique=True, blank=False)
    rfid_id = models.CharField(max_length=200, unique=True, blank=False)
    crd = models.DateTimeField(blank=False, auto_now_add=True)
    valid_to = models.DateTimeField(blank=False, default=timezone.now() + timezone.timedelta(minutes=5))


class CustomUser(AbstractUser):
    username = models.CharField(max_length=200, unique=True)
    email = models.EmailField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    is_moderator = models.BooleanField(default=False)
    storage = models.OneToOneField(Storage, null=True, on_delete=models.SET_NULL)
    rfid_id = models.CharField(max_length=20, blank=True, default=None, null=True)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email']


class Allergies(models.Model):
    name = models.CharField(max_length=200, unique=True)
    tej = models.BooleanField()
    gluten = models.BooleanField()
    hus = models.BooleanField()
    tojas = models.BooleanField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    difficulty = models.IntegerField()
    description = models.TextField()
    allergies = models.ForeignKey(Allergies, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(blank=True, null=True, default=None, upload_to="recipes")

    def mask_pk(self):
        return settings.FERNET.encrypt(str(self.pk).encode()).decode()

    def __str__(self):
        return f"{self.name} ({self.allergies})"


class PreIngredients(models.Model):
    group = models.IntegerField()
    measure = models.CharField(max_length=200)
    multiply = models.IntegerField()

    def __str__(self):
        return self.measure


class AllIngredients(models.Model):
    name = models.CharField(max_length=200)
    group = models.IntegerField()

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    unit = models.CharField(max_length=200)
    measure = models.DecimalField(max_digits=10, decimal_places=2)
    recipe = models.ForeignKey(Recipe, on_delete=models.DO_NOTHING, blank=True, null=True)
    storage = models.ForeignKey(Storage, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return f"{self.name}: \t{self.measure} {self.unit}"

loginApp/views.py
import json
import logging

from django.contrib import messages  # import messages
from django.contrib.auth import authenticate
from django.core.paginator import Paginator
from django.contrib.auth import login, logout
from django.contrib.auth.models import Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view

from . import forms
from . import utils
from .serialize import ApiModelSerializer
from .models import Recipe, Allergies, Category, Ingredient, PreIngredients, AllIngredients, APIModel, CustomUser
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from imap_tools import MailBox, AND

imap = MailBox(settings.IMAP_HOST).login(settings.IMAP_USERNAME, settings.IMAP_PASSWORD)

logger = logging.getLogger(__name__)


# Create your views here.


@login_required(login_url="/recipes/login?next=/recipes/recipe_list")
def homepage(request):
    return render(request, "loginApp/home.html")


def permission_denied(request):
    if request.method == 'GET':
        perm_codename = request.GET.get('perm', None)
    if perm_codename:
        perm = Permission.objects.get(codename=perm_codename)

    return render(request, 'loginApp/permissionPopUp.html', {'perm': perm})


@api_view(['POST'])
@csrf_exempt
def save_api_call(request):
    if request.method == 'POST':
        saveserialize = ApiModelSerializer(data=request.data)
        if saveserialize.is_valid():
            saveserialize.save()
            return Response(saveserialize.data, status=status.HTTP_201_CREATED)


def recipe_to_pdf(request, recipe_id):
    recipe_id = settings.FERNET.decrypt(recipe_id.encode()).decode()
    recipe_obj = Recipe.objects.get(pk=recipe_id)
    ings = Ingredient.objects.filter(recipe_id=recipe_id)
    pdf = utils.render_to_pdf('../templates/sablon/recipe.html', {'recipe': recipe_obj, 'ings': ings})
    return FileResponse(pdf, content_type='application/pdf')


@login_required(login_url="/recipes/login?next=/recipes/recipe_list")
def recipe_list(request):
    lista = Recipe.objects.all().order_by('name', 'difficulty')
    page_number = request.GET.get('page')
    page_count = request.GET.get('count', 10)

    paginator = Paginator(lista, page_count)

    # unseen emails list from imap
    emails = [msg for msg in imap.fetch(AND(seen=False))]

    print(len(emails))

    page_obj = paginator.get_page(page_number)

    return render(request, "loginApp/recipes.html", {'QuerySet': page_obj, 'per_page': page_obj.paginator.per_page})


def register_request(request):
    if request.method == "POST":
        form = forms.NewUserForm(request.POST, initial={"moderator": False})
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            plaintext = get_template('loginApp/email.txt')
            htmly = get_template('loginApp/emailTemplate.html')

            subject, from_email, to_email = 'registration successfully', 'noreply@sativus.space', user.email

            text_content = plaintext.render({'user': user})
            html_content = htmly.render({'user': user})

            msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

            return redirect("loginApp:homepage")
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
            return render(request=request, template_name="loginApp/register.html", context={"register_form": form})
    form = forms.NewUserForm
    return render(request=request, template_name="loginApp/register.html", context={"register_form": form})


@login_required(login_url="/recipes/login?next=/recipes/recipe_list")
@permission_required(raise_exception=False, login_url='/recipes/permission?perm=change_allergies',
                     perm="change_allergies")
def update_allergie(request, allergies_id):
    obj = get_object_or_404(Allergies, id=allergies_id)
    if request.method == "POST":
        form = forms.AllergiesFrom(request.POST, instance=obj, formstate='update')
        if form.is_valid():
            instance = form.save()
            # return redirect("loginApp:allergies")
            return HttpResponse(
                '<script>opener.closePopup(window, "%s", "%s", "#id_allergie");</script>' % (instance.pk, instance))
        else:
            messages.error(request, "Hiba történt a mentés során")
            return render(request, "loginApp/allergies_detail.html", {"form": form, 'obj_id': obj.pk})
    else:
        form = forms.AllergiesFrom(instance=obj, formstate='update')
    return render(request, "loginApp/allergies_detail.html", {"form": form, 'obj_id': obj.pk})


@csrf_exempt
def get_allergies_id(request):
    if request.is_ajax():
        allergies_name = request.GET['name']
        allergies_id = Allergies.objects.get(name=allergies_name).pk
        data = {'allergies_id': allergies_id, }

        return HttpResponse(json.dumps(data), content_type='application/json')
    return HttpResponse("/")


def view_allergie(request, allergies_id):
    obj = get_object_or_404(Allergies, id=allergies_id)
    form = forms.AllergiesFrom(request.POST, instance=obj, formstate='view')
    return render(request, "loginApp/allergies_detail.html", {"form": form})


def add_allergie(request):
    if request.method == "POST":
        form = forms.AllergiesFrom(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.info(request, "Mentés sikeres!")
            # return redirect("loginApp:allergies")
            return HttpResponse(
                '<script>opener.closePopup(window, "%s", "%s", "#id_allergies");</script>' % (instance.pk, instance))
        else:
            messages.error(request, "hiba törtent a mentés soran")
            return render(request, "loginApp/allergies_detail.html", {"form": form})
    form = forms.AllergiesFrom()
    return render(request, "loginApp/allergies_detail.html", {"form": form})


def del_allergies(request, allergies_id):
    obj = Allergies.objects.get(pk=allergies_id)
    obj.delete()
    return HttpResponse(
        '<script>opener.closePopupDel(window, "%s", "%s", "#id_allergies");</script>' % (obj.pk, obj))


def api_login(request):
    username = request.GET.get("username", None)
    if username:
        try:
            user_in_api_table = APIModel.objects.get(username=username)
            user = CustomUser.objects.get(username=username)
            current_date = timezone.now()
            if user_in_api_table.valid_to > current_date and user.rfid_id == user_in_api_table.rfid_id:
                login(request, user)
            else:
                user_in_api_table.delete()
                messages.error(request, "RFID belepes sikertelen (lejart az ido vagy a kartya azonosito nem egyezik)")
                form = AuthenticationForm()
                return render(request=request, template_name="loginApp/login.html", context={"login_form": form})

            if user.is_authenticated:
                user_in_api_table.delete()

            return redirect("loginApp:homepage")
        except APIModel.DoesNotExist:
            messages.error(request, "RFID belepes sikertelen")
            form = AuthenticationForm()
            return render(request=request, template_name="loginApp/login.html", context={"login_form": form})

    return HttpResponse(status=status.HTTP_400_BAD_REQUEST)


def login_request(request):
    next_url = request.GET.get("next", None)
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Sikeresen bejelentkeztél {username}.")
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect("loginApp:recipes")
            else:
                messages.error(request, "Hibás felhasználónév vagy jelszó")
        else:
            messages.error(request, "Hibás felhasználónév vagy jelszó")
    form = AuthenticationForm()
    return render(request=request, template_name="loginApp/login.html", context={"login_form": form})


@login_required(login_url="/recipes/login?next=/recipes/recipe_list")
def add_recipe(request):
    if request.method == "POST":
        form = forms.RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request, "Mentés sikeres!")
            return redirect("loginApp:recipes")
        else:
            messages.error(request, "hiba törtent a mentés soran")
            return render(request, "loginApp/add_recipe.html", {"recipe_form": form})
    form = forms.RecipeForm()
    return render(request, "loginApp/add_recipe.html", {"recipe_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Sikeresen kijelentkeztél")
    return redirect("loginApp:homepage")


def allergiesList(request):
    obj = Allergies.objects.all().order_by('pk')
    paginator = Paginator(obj, 10)

    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)

templates/loginApp/allergies.html
{% extends "loginApp/header.html" %}

{% block title %}Allergenek{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'loginApp:add_allergie' %}">új</a>
    <table class="table table-bordered table-striped">
        <tr>
            <th>id</th>
            <th>tej</th>
            <th>gluten</th>
            <th>hus</th>
            <th>tojas</th>
        </tr>
        {% if page_obj %}
            {% for allergie in page_obj %}
                <tr>
                    <td>{{ allergie.id }}</td>
                    <td>{{ allergie.tej|yesno:"+,,talan" }}</td>
                    <td>{{ allergie.gluten|yesno:"+,,talan" }}</td>
                    <td>{{ allergie.hus|yesno:"+,,talan" }}</td>
                    <td>{{ allergie.tojas|yesno:"+,,talan" }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="5">Nincs talalat</td>
            </tr>
        {% endif %}
    </table>
{% endblock %}

templates/loginApp/allergies_detail.html
{% extends "loginApp/popUpTemplate.html" %}

{% load crispy_forms_tags %}

{% block title %}Allergén részletek{% endblock%}
{% block content %}
    {% if obj_id %}
    <a class="btn btn-danger" href="{% url 'loginApp:allergies_del' allergies_id=obj_id %}">Törlés</a>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <a id="backButton" class="btn btn-danger">Vissza</a>
        {% if user.is_authenticated and form.formstate == 'update'%}
            <button class="btn btn-success" type="submit">Mentes</button>
        {% endif %}

    </form>
{% endblock %}

templates/loginApp/categories.html
{% extends "loginApp/header.html" %}

{% block title %}Kategóriák{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'loginApp:add_category' %}">új</a>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Id</th>
            <th>Nev</th>
        </tr>
        {% if QuerySet %}
            {% for category in QuerySet %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">Nincs talalat</td>
            </tr>
        {% endif %}
    </table>
{% endblock %}

templates/loginApp/emailTemplate.html
<!DOCTYPE html>
<html>
<body>
<h1>Hello {{ user.username }}</h1>
<p> Congratulation, you are successfully registered on djangoTestSite with username: {{ user.username }} email address: {{ user.email }}</p>
</body>
</html>

templates/loginApp/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" type="image/png" href="{% static 'loginApp/favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'loginApp/css/default.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <script src="https://kit.fontawesome.com/d750f44ba8.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>



    <title>
        {% block title %}

        {% endblock %}
    </title>
  </head>
 <body>
 <!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'homepage' %}">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'loginApp:logout' %}">Logout</a>
      </li>
      {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginApp:login' %}">Login</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginApp:register' %}">Register</a>
          </li>
      {% endif %}

      <li class="nav-item">
          <a class="nav-link" href="{% url 'loginApp:recipes' %}">Recipes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chatApp:homepage' %}">ChatApp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'smartHome:homepage' %}">SmartHome</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'codenames:homepage' %}">Codenames</a>
      </li>



    </ul>

  {% if user.is_authenticated %}
      <span class="navbar-text">
        <a class="navbar-link" href="#">Welcome, {{user.username}}</a>
      </span>
  {% endif %}
  </div>
</nav>

    {% if messages %}
        <div class="container mt-4">
    <ul>
        {% for message in messages %}
            <li><div class="pt-2">{{ message }}</div></li>
        {% endfor %}
    </ul>
        </div>
    {% endif %}

    <div class="container mt-4">
    {% block content %}

    {% endblock %}
    </div>

 {% if QuerySet %}
 <div class="pagination mt-4 d-flex justify-content-center">
    <span class="step-links">
        {% if QuerySet.has_previous %}
            <a href="?page=1}&count={{ per_page }}" class="btn btn-primary">&laquo; first</a>
            <a href="?page={{ QuerySet.previous_page_number }}}&count={{ per_page }}" class="btn btn-primary">previous</a>
        {% endif %}

        <span class="current badge badge-pill badge-info">
            Page {{ QuerySet.number }} of {{ QuerySet.paginator.num_pages }}.
        </span>
        <select id="paginatorSelect" onchange="changePaginator(this, '{{ request.path }}')">
            <option value="10">10</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="20">20</option>
            <option value="50">50</option>
            <option value="100">100</option>
            <option value="1000">1000</option>
        </select>

        {% if QuerySet.has_next %}
            <a href="?page={{ QuerySet.next_page_number }}&count={{ per_page }}" class="btn btn-primary">next</a>
            <a href="?page={{ QuerySet.paginator.num_pages }}&count={{ per_page }}" class="btn btn-primary">last &raquo;</a>
        {% endif %}
    </span>
</div>
 {% endif %}
    <script type="text/javascript" src="{% static 'loginApp/js/default.js' %}" ></script>
    <script type="text/javascript">
        $("#paginatorSelect").val({{per_page}});
    </script>
    {% block script %}

    {% endblock %}

  </body>
</html>

templates/loginApp/ingredients.html
{% extends "loginApp/header.html" %}

{% block title %}Hozzávalók{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'loginApp:add_ingredient' %}">új</a>
    <table class="table table-bordered table-striped">
        <tr>
            <th>id</th>
            <th>Nev</th>
            <th>Mennyiseg</th>
            <th>Mertekegyseg</th>
            <th>Recept id</th>
            <th>Storage id</th>
        </tr>
        {% if page_obj %}
            {% for ing in page_obj %}
                <tr>
                    <td>{{ ing.id }}</td>
                    <td>{{ ing.name }}</td>
                    <td>{{ ing.measure }}</td>
                    <td>{{ ing.unit }}</td>
                    <td>{{ ing.recipe.pk }}</td>
                    <td>{{ ing.storage.pk }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6">Nincs talalat</td>
            </tr>
        {% endif %}
    </table>
{% endblock %}

templates/loginApp/recipes.html
{% extends 'loginApp/header.html' %}
{% load custom_filters %}

{% block title %}Receptek{% endblock %}

{% block content %}

{% if perms.add_recipe %}
<a class="btn btn-primary" style="display: inline" href="{% url 'loginApp:add_recipe' %}">új</a>
{% endif %}
<a class="btn btn-primary" style="display: inline" href="{% url 'loginApp:storage' %}">raktáram</a>

<table class="table table-bordered table-striped mt-2">
<tr>
    <th>Név</th>
    <th>Kategória</th>
    <th>Nehézség</th>
    <th>Muveletek</th>
</tr>
{% if QuerySet %}
    {% for recipe in QuerySet %}
        <tr>
            <td>{{ recipe.name }}</td>
            <td>{{ recipe.category }}</td>
            <td>{{ recipe.difficulty }}</td>
            <td>
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'loginApp:recipe_edit' recipe.mask_pk %}">szerkeszt</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'loginApp:recipe_view' recipe.mask_pk %}">megnéz</a>
                {% if user.is_authenticated %}
                <a class="btn btn-danger" href="{% url 'loginApp:recipe_delete' recipe.mask_pk %}">Torles</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}

{% else %}
    <td colspan="3">Nincs talalat</td>
{% endif %}
</table>


{% endblock %}

templates/loginApp/storage.html
{% extends 'loginApp/header.html' %}
{% load custom_filters %}

{% block title %}Raktár{% endblock %}

{% block content %}

<a class="btn btn-danger" style="display: inline" href="{% url 'loginApp:recipes' %}">Vissza</a>
<a class="btn btn-primary" href="{% url 'loginApp:add_ingredient' %}?selected_name_id=1&storage_id={{ user.storage }}" id="add_ingredient" onclick="return showAddPopup(this)">új hozzávaló</a>



<table class="table table-bordered table-striped mt-2">
<tr>
    <th>Név</th>
    <th>Mennyiség</th>
    <th>Egység</th>
    <th>Műveletek</th>
</tr>
{% if ings %}
    {% for ing, group in ings %}
        <tr>
            <td>{{ ing.name }}</td>
            <td>{{ ing.measure | upscale_measure:group }}</td>
            <td>{{ ing.unit }}</td>
            <td>
                <a id="view_ingredient" name="{{ ing.pk }}" style="cursor: pointer; cursor: hand;"><i class="fas fa-eye"></i></a>
                <a id="edit_ingredient" name="{{ ing.pk }}" style="cursor: pointer; cursor: hand"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'loginApp:ingredient_del' ing.pk %}?parent={{ request.path }}"><i class="fas fa-times"></i></a>
            </td>
        </tr>
    {% endfor %}

{% else %}
    <td colspan="4">Nincs talalat</td>
{% endif %}
</table>


{% endblock %}