chatApp/urls.py
from django.urls import path

from . import views

app_name = 'chatApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),

]

loginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings
from . import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('loginApp.urls'), name='loginApp'),
    path('home/', include('smartHome.urls'), name='smartHome'),
    path('chat/', include('chatApp.urls'), name='chatApp'),
    path('codenames/', include('codenames.urls'), name='codenames'),
    path('', homepage.homepage, name='homepage')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import random

chatrooms = {}

# Create your views here.


@login_required(login_url='/recipes/login?next=/chat/')
def homepage(request):
    return render(request, 'chatApp/home.html')


@login_required(login_url='/recipes/login?next=/chat/')
def create_room(request):
    if request.method == 'GET':
        room_id = random.randint(1000, 9999)
        while room_id in chatrooms.keys():
            room_id = random.randint(1000, 9999)
        chatrooms[room_id] = 1

        print("A szoba azonositoja", room_id)
        return render(request, 'chatApp/room.html', {"room_id": room_id})

    return render(request, 'chatApp/home.html', {"error": 'Valami hiba tortent a szoba letrehozasanal!'})


@login_required(login_url='/recipes/login?next=/chat/')
def join_room(request):
    if request.method == 'POST':
        join_code = request.POST.get('joinCode', None)

        if join_code:
            return render(request, 'chatApp/room.html', {'room_id': join_code})


def exit_room(request):
    return render(request, 'chatApp/home.html', {})

templates/chatApp/home.html
{% extends "loginApp/header.html" %}

{% block title %}Fokepernyo{% endblock %}

{% block content %}
{% if user.is_authenticated %}



    <h1>Hello {{ user.username }}</h1>
    <a href="{% url 'chatApp:create_room' %}" class="btn btn-primary mb-3">Szoba letrehozasa</a>

    <form action="{% url 'chatApp:join_room' %}" method="post">
    <div class="form-group">
        {% csrf_token %}
    <input id="joinCode" name="joinCode" class="form-control" type="number" size="4" placeholder="Room join code" />
    <input type="submit" class="btn btn-success mt-3" value="csatlakozas" />
    </div>

    </form>

{% endif %}

{% endblock %}

templates/chatApp/room.html
{% extends 'loginApp/header.html' %}

{% block title %}{{ room_id }} számú szoba{% endblock %}

{% block content %}

    <div class="flex-container mt-4">
        <h2>#{{ room_id }} szoba</h2>
    </div>

    <div class="flex-container mt-4" style="width: 100%;height: 95%" id="chatLog">
    </div>

    <div class="row ml-1" style="height: 5%">
        <input  type="text" style="width: 93%" class="mr-2" id="textMessage">
        <input type="button" class="btn btn-primary" value="Send" id="sendBtn">
    </div>

    {{ room_id|json_script:"room-id" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-id').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            let div = document.createElement('div');
            let p = document.createElement('div');


            console.log(data.sender);

            if (data.sender == "{{ user.username }}") {
                p.innerText = data.message;
                div.className = "d-flex justify-content-end mb-2";
                p.className = "px-2 mx-2 rounded bg-primary text-light"
            } else {
                div.className = "d-flex justify-content-start mb-4";
                p.innerText = data.sender + ": " + data.message;
                p.className = "px-2 mx-2 rounded bg-danger text-light"
            }

            div.appendChild(p);

            document.querySelector('#chatLog').appendChild(div);
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
            window.location.href = "{% url 'chatApp:exit_room' %}";
        };

        document.querySelector('#textMessage').focus();
        document.querySelector('#textMessage').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#sendBtn').click();
            }
        };

        document.querySelector('#sendBtn').onclick = function(e) {
            const messageInputDom = document.querySelector('#textMessage');
            const message = messageInputDom.value;

            var kimenoDiv = document.createElement('div');
            var p = document.createElement('p');
            p.innerText = message;
            kimenoDiv.className = "d-flex justify-content-end mb-4";
            kimenoDiv.appendChild(p);

            chatSocket.send(JSON.stringify({
                'sender': "{{ user.username }}",
                'message': message
            }));
            messageInputDom.value = '';


        };
    </script>

{% endblock %}